name: Godot Builder

env:
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    DISCORD_USERNAME: The Blob
    uses: Ilshidur/action-discord@master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]
jobs:
  Builder:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/greenfox/godot-build-automation:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Godot Project
      run: |
        builder
