name: Itch.io Push

on:
  release:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: josephbmanley/butler-publish-itchio-action@master
    env:
      BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      CHANNEL: windows
      ITCH_GAME: It Spreads
      ITCH_USER: username
      PACKAGE: build/windows
